# Config file for automatic testing at travis-ci.org

sudo: required
services:
  - docker
language: python
python:
  - 2.7


# command to run tests, e.g. python setup.py test
script: 
  - docker build -t testimage . 

# deploy new versions to PyPI
deploy:
  provider: pypi
  distributions: sdist 
  user: audreyr
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: ashmastaflash/python_boilerplate
    python: 2.7
